import { PricingRule, RiderProfile } from "./types";

export const MOCK_RIDERS: RiderProfile[] = [
  {
    id: 1,
    user_id: 10,
    vehicle_type: "moto",
    vehicle_plate_number: "RAE 123 A",
    vehicle_color: "Black",
    national_id: "1199880011223344",
    driving_license_number: "DL-123456",
    status: "pending",
    is_online: false,
    user: {
      id: 10,
      role: "rider",
      name: "Jean Claude Niyonsaba",
      username: "jean.claude",
      email: "jean@example.com",
      phone: "250788111222",
    },
    created_at: "2026-07-01T10:00:00Z",
  },
  {
    id: 2,
    user_id: 11,
    vehicle_type: "moto",
    vehicle_plate_number: "RAF 456 B",
    vehicle_color: "Red",
    national_id: "1199880011223355",
    driving_license_number: "DL-654321",
    status: "approved",
    is_online: true,
    user: {
      id: 11,
      role: "rider",
      name: "Eric Manzi",
      username: "eric.manzi",
      email: "eric@example.com",
      phone: "250788654321",
    },
    created_at: "2026-06-15T08:00:00Z",
  },
  {
    id: 3,
    user_id: 12,
    vehicle_type: "bicycle",
    vehicle_plate_number: null,
    vehicle_color: "Blue",
    national_id: "1199880011223366",
    driving_license_number: null,
    status: "approved",
    is_online: false,
    user: {
      id: 12,
      role: "rider",
      name: "Aline Umuhoza",
      username: "aline.umuhoza",
      email: "aline.rider@example.com",
      phone: "250788333444",
    },
    created_at: "2026-06-20T12:00:00Z",
  },
  {
    id: 4,
    user_id: 13,
    vehicle_type: "moto",
    vehicle_plate_number: "RAG 789 C",
    vehicle_color: "White",
    national_id: "1199880011223377",
    driving_license_number: "DL-999888",
    status: "rejected",
    is_online: false,
    rejection_reason: "Driving license document is missing.",
    user: {
      id: 13,
      role: "rider",
      name: "Patrick Habimana",
      username: "patrick.h",
      email: "patrick@example.com",
      phone: "250788555666",
    },
    created_at: "2026-06-28T14:00:00Z",
  },
  {
    id: 5,
    user_id: 14,
    vehicle_type: "car",
    vehicle_plate_number: "RAH 012 D",
    vehicle_color: "Silver",
    national_id: "1199880011223388",
    driving_license_number: "DL-111222",
    status: "suspended",
    is_online: false,
    admin_notes: "Suspended because of customer complaint.",
    user: {
      id: 14,
      role: "rider",
      name: "Grace Mukamana",
      username: "grace.m",
      email: "grace@example.com",
      phone: "250788777888",
    },
    created_at: "2026-05-10T09:00:00Z",
  },
];

export const MOCK_PRICING_RULES: PricingRule[] = [
  {
    id: 1,
    name: "Akamoto Moto Standard",
    vehicle_type: "moto",
    base_distance_km: 3,
    base_price: 1000,
    extra_price_per_km: 200,
    minimum_price: 0,
    commission_percentage: 20,
    currency: "RWF",
    is_active: true,
  },
  {
    id: 2,
    name: "Akamoto Bicycle Standard",
    vehicle_type: "bicycle",
    base_distance_km: 3,
    base_price: 600,
    extra_price_per_km: 100,
    minimum_price: 0,
    commission_percentage: 20,
    currency: "RWF",
    is_active: true,
  },
  {
    id: 3,
    name: "Akamoto Car Standard",
    vehicle_type: "car",
    base_distance_km: 3,
    base_price: 3000,
    extra_price_per_km: 500,
    minimum_price: 0,
    commission_percentage: 20,
    currency: "RWF",
    is_active: true,
  },
  {
    id: 4,
    name: "Akamoto Van Standard",
    vehicle_type: "van",
    base_distance_km: 3,
    base_price: 4000,
    extra_price_per_km: 600,
    minimum_price: 0,
    commission_percentage: 15,
    currency: "RWF",
    is_active: false,
  },
];

export function getMockRider(id: number): RiderProfile | undefined {
  return MOCK_RIDERS.find((r) => r.id === id);
}

export function getMockPricingRule(id: number): PricingRule | undefined {
  return MOCK_PRICING_RULES.find((r) => r.id === id);
}
